### ISSUE TITLE
Two encode jobs get started at the same time

### ISSUE THREAD

**Issue by TheFiZi** [ahnooie/automatic-ripping-machine#72]
Ripping Blurays, had the same problem with HDVDs, it appears the part of the script that calls Handbreak doens't check if Handbreak is already encoding so I constantly have two jobs running which makes things take a lot longer.

Not sure what you need from me to troubleshoot things.

**Comment by ahnooie** [comment]
This is intended behavior.  The ARM scripts calls the transcoding command with "batch" which waits until the system load is below 1.5 and then queues the next transcoding job.  The only way you got two transcoding jobs running simultaneously is that your system load fell below 1.5 which generally means you had CPU cycles to spare (unless you're running a 1 core CPU).  This is not going to be perfect for every system but overall I think it's a good compromise between running everything in serial and not maximizing the cpu and running it all in parallel and it takes forever to finish transcoding.

The only way I can think of to make this better is to use the atd command instead of batch where you can specify the desired load before the command executes instead of the default of 1.5.

**Comment by TheFiZi** [comment]
Thanks for the explanation. I'm using a 4 CPU VM to do my transcoding so there must have been spare CPU cycles lying around.

**Comment by ahnooie** [comment]
Hmmm.  I bet both jobs are in the queue waiting and finally when the CPU drops below 1.5 both jobs launch at the same time.

**Comment by TheFiZi** [comment]
That's my guess as well based on your explanation of how the batch process works.
